before_script:
 - ln -s ./Makefile.standalone Makefile
 - which uncrustify
 - which doxygen
 - which tree
 - uname -a

stages:
 - build
 - test
 - release

buildlib:
 stage: build
 tags: 
  - shell
  - freebsd
 script:
  - make
  - tree stage/libifc
 artifacts:
  name: "libifc"
  paths:
   - stage/libifc/

buildlib_in_base:
 stage: build
 tags:
  - shell
  - freebsd
 script:
  make -f Makefile.ci buildlibinbase

verify_style9:
 stage: test
 tags: 
  - shell
  - uncrustify
 script:
  - make -f Makefile.ci checkstyle

doxygen:
 stage: release
 tags: 
  - shell
  - doxygen
 script:
  - make doxygen
 artifacts:
  paths:
   - stage/doxygen/

freebsd_base_dist:
 stage: release
 tags:
  - shell
 script:
  - make -f Makefile.ci createfreebsdtree
  - tree stage/freebsdsrc
 artifacts:
  paths:
   - stage/freebsdsrc
